### ISSUE TITLE
returning the transaction id from AttributeDecodeFailure

### ISSUE THREAD

**Issue by jxs** [Vagr9K/rust-stun-coder#2]
Hi again, 
when decoding a message, if the attribute type is unrecognized `AttributeDecodeFailure` is returned, but as the transaction id is missing one cannot use it to return a [`420  Unknown Attribute`](https://datatracker.ietf.org/doc/html/rfc5389#section-15.6). What do you think of adding the transaction id to `MessageDecodeError` and converting it to a struct instead of an enum and add the `Option<transaction_id>` there (I have done similar [here](https://github.com/rust-db/refinery/blob/99e1f875e2438b9fb60905d225b6c7d622b505a5/refinery_core/src/error.rs#L8-L11))?

**Comment by Vagr9K** [comment]
Hey!

Makes sense to me given the circumstances.

If you're interested in creating a PR for it I'll make sure to review and merge it.
